Task
Project-Skill-Tree/Skill-Tree-API pull request #32
Opened 2022-06-06 10:19 UTC by seanjhardy

Long overdue for a merge pls make it happen. Pretty much contains all of everything

2022-06-08 20:53 UTC, seanjhardy commented
The longer this goes the more shit I'm going to add

2022-06-09 03:15 UTC, swatarianess requested changes

2022-06-09 03:15 UTC, swatarianess commented on src/loaders/mongooseLoader.js
>    mongoose.connect(process.env.DB_KEY).catch(error => console.error(error));
Would recommend replacing with this;
```js
mongoose.connect(URL, {useNewUrlParser: true, useUnifiedTopology: true}, (err) => {
    if (err){
      log.warn("Error",err)
    } else{
      log.info("Connected to db successfully")
    }
  });
  ```

2022-06-09 09:05 UTC, swatarianess approved these changes

2022-06-14 10:17 UTC, OmerSabic approved these changes

2022-06-28 05:32 UTC, merged